x-templates:
  x-fasset-bot-template: &fasset-bot
    image: ghcr.io/flare-foundation/fasset-bots:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

services:
  postgres:
    profiles: [agent,liquidator,challenger,cli]
    image: postgres:15
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${FASSET_DB_NAME}
      POSTGRES_USER: ${FASSET_DB_USER}
      POSTGRES_PASSWORD: ${FASSET_DB_PASSWORD}
      POSTGRES_PORT: 5432
      DEBUG: "true"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $FASSET_DB_USER -d ${FASSET_DB_NAME} -h 127.0.0.1"]
      timeout: 20s
      retries: 10

  app:
    <<: *fasset-bot
    profiles: [agent]
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      FRONTEND_PASSWORD: ${FRONTEND_PASSWORD}
      ROOT_PATH: ${BACKEND_PATH:-}
      LOG_TARGET: ${LOG_TARGET:-}
      FASSET_BOT_CONFIG: "./config.json"
      FASSET_BOT_SECRETS: "./secrets.json"
    ports:
      - "$BACKEND_PORT:1234"
    volumes:
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/app:/usr/src/app/log/
    command: "./entry.sh run-bots"

  liquidator:
    <<: *fasset-bot
    profiles: [liquidator]
    container_name: ${COMPOSE_PROJECT_NAME}-liquidator
    volumes:
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/liquidator:/usr/src/app/log/
    environment:
      LOG_TARGET: ${LOG_TARGET}
      FASSET_BOT_CONFIG: "./config.json"
      FASSET_BOT_SECRETS: "./secrets.json"
    command: "./entry.sh run-liquidator"

  challenger:
    <<: *fasset-bot
    profiles: [challenger]
    container_name: ${COMPOSE_PROJECT_NAME}-challenger
    volumes:
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/challenger:/usr/src/app/log/
    environment:
      LOG_TARGET: ${LOG_TARGET}
      FASSET_BOT_CONFIG: "./config.json"
      FASSET_BOT_SECRETS: "./secrets.json"
    command: "./entry.sh run-challenger"

  agent-bot:
    <<: *fasset-bot
    profiles: [cli]
    container_name: ${COMPOSE_PROJECT_NAME}-agent-bot
    volumes:
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/agent-bot:/usr/src/app/log/
    entrypoint: ["yarn", "agent-bot"]
    environment:
      FASSET_BOT_CONFIG: "./config.json"
      FASSET_BOT_SECRETS: "./secrets.json"

  user-bot:
    <<: *fasset-bot
    profiles: [cli]
    container_name: ${COMPOSE_PROJECT_NAME}-user-bot
    volumes:
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/user-bot:/usr/src/app/log/
    entrypoint: ["yarn", "user-bot"]
    environment:
      FASSET_USER_SECRETS: "./secrets.json"
      FASSET_USER_CONFIG: "./config.json"

  ui:
    profiles: [agent-ui]
    image: ghcr.io/flare-labs-ltd/fasset-agent-ui:latest
    container_name: ${COMPOSE_PROJECT_NAME}-ui
    restart: unless-stopped
    environment:
      API_URL: ${FRONTEND_API_URL}
      WALLETCONNECT_PROJECT_ID: ${WALLETCONNECT_PROJECT_ID}
      FRONT_URL: ${FRONTEND_PATH:-}
      FRONTEND_URL: ${FRONTEND_PATH:-}
    ports:
      - "$FRONTEND_PORT:3000"
    command: "/bin/sh -c '(npm run build) && (npm run start)'"
    stdin_open: true
    tty: true

volumes:
  postgres-db: