services:
  postgres:
    profiles: [agent,liquidator,challenger]
    image: postgres:15
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: ${FASSET_DB_NAME}
      POSTGRES_USER: ${FASSET_DB_USER}
      POSTGRES_PASSWORD: ${FASSET_DB_PASSWORD}
      DEBUG: "true"
    # for testing
    #ports:
    #  - "15432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $FASSET_DB_USER -d ${FASSET_DB_NAME} -h 127.0.0.1"]
      timeout: 20s
      retries: 10

  app:
    profiles: [agent]
    #image: fasset-bots
    image: ghcr.io/flare-labs-ltd/fasset-bots:songbird-release
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      DB_NAME: ${FASSET_DB_NAME}
      DB_HOST: postgres
      DB_PORT: ${FASSET_DB_PORT}
      DB_USER: ${FASSET_DB_USER}
      DB_PASSWORD: ${FASSET_DB_PASSWORD}
      FASSET_DB_USER: ${FASSET_DB_USER}
      FASSET_DB_PASSWORD: ${FASSET_DB_PASSWORD}
      FRONTEND_PASSWORD: ${FRONTEND_PASSWORD}
      ROOT_PATH: ${FRONTEND_BACKEND_PATH}
    # for back-end
    ports:
      - "$BACKEND_PORT:1234"
    volumes:
      - ./.env:/usr/src/app/.env
      - ./config/.env.bots-api:/usr/src/app/packages/fasset-bots-api/.env
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      # export logs
      - ./log/app:/usr/src/app/log/
      - ./log/app-bots-api:/usr/src/app/packages/fasset-bots-api/log/

    # Start run-agent and ui backend
    command: "./entry.sh run-bots"

    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  liquidator:
    profiles: [liquidator]
    image: ghcr.io/flare-labs-ltd/fasset-bots:songbird-release
    container_name: ${COMPOSE_PROJECT_NAME}-liquidator
    volumes:
      - ./.env:/usr/src/app/.env
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      # export logs
      - ./log/liquidator:/usr/src/app/log/

    # Start run-agent and ui backend
    command: "./entry.sh run-liquidator"

    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  challenger:
    profiles: [challenger]
    image: ghcr.io/flare-labs-ltd/fasset-bots:songbird-release
    container_name: ${COMPOSE_PROJECT_NAME}-challenger
    volumes:
      - ./.env:/usr/src/app/.env
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      # export logs
      - ./log/challenger:/usr/src/app/log/

    # Start run-agent and ui backend
    command: "./entry.sh run-challenger"

    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  agent-bot:
    profiles: [cli]
    image: ghcr.io/flare-labs-ltd/fasset-bots:songbird-release
    container_name: ${COMPOSE_PROJECT_NAME}-agent-bot
    volumes:
      - ./.env:/usr/src/app/.env
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/agent-bot:/usr/src/app/log/
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["yarn", "agent-bot"]

  user-bot:
    profiles: [cli]
    image: ghcr.io/flare-labs-ltd/fasset-bots:songbird-release
    container_name: ${COMPOSE_PROJECT_NAME}-user-bot
    volumes:
      - ./.env:/usr/src/app/.env
      - ./secrets.json:/usr/src/app/secrets.json
      - ./config.json:/usr/src/app/config.json
      - ./log/user-bot:/usr/src/app/log/
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["yarn", "user-bot"]

  ui:
    profiles: [agent-ui]
    image: ghcr.io/flare-labs-ltd/fasset-agent-ui:songbird-release
    container_name: ${COMPOSE_PROJECT_NAME}-ui
    environment:
      API_URL: ${FRONTEND_BACKEND_URL}
      FRONT_URL: ${FRONTEND_PATH}
      FRONTEND_URL: ${FRONTEND_URL}
      WALLETCONNECT_PROJECT_ID: ${WALLETCONNECT_PROJECT_ID}
    ports:
      - "$FRONTEND_PORT:3000"
    volumes:
      - ./.env:/app/.env

    # Start with running the agent
    command: "/bin/sh -c '(npm run build) && (npm run start)'"

    stdin_open: true
    tty: true

volumes:
  postgres-db:
